[options]
; Conexion a base de datos
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo_t41l0r1ng_2024
db_name = False

; Rutas de addons
addons_path = /opt/odoo/odoo/addons,/opt/odoo/extra-addons

; Directorio de datos
data_dir = /var/lib/odoo

; Seguridad
admin_passwd = TailoringAdmin2024!
list_db = True

; Rendimiento
workers = 2
max_cron_threads = 1
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 600
limit_time_real = 1200

; Logging
log_level = info
logfile = /var/lib/odoo/odoo-server.log

; Interfaz
http_port = 8069
proxy_mode = True
